# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/jlepain/PycharmProjects/Perso/JDD/JDD/IHM/main_windows\main.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(435, 360)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(435, 360))
        MainWindow.setMaximumSize(QtCore.QSize(435, 360))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(415, 0))
        self.label_3.setMaximumSize(QtCore.QSize(415, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_score = QtWidgets.QLabel(self.centralwidget)
        self.label_score.setMinimumSize(QtCore.QSize(300, 30))
        self.label_score.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_score.setFont(font)
        self.label_score.setObjectName("label_score")
        self.horizontalLayout_2.addWidget(self.label_score)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_question = QtWidgets.QLabel(self.centralwidget)
        self.label_question.setMinimumSize(QtCore.QSize(415, 30))
        self.label_question.setMaximumSize(QtCore.QSize(415, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_question.setFont(font)
        self.label_question.setAlignment(QtCore.Qt.AlignCenter)
        self.label_question.setObjectName("label_question")
        self.verticalLayout.addWidget(self.label_question)
        self.LE_reponse = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LE_reponse.sizePolicy().hasHeightForWidth())
        self.LE_reponse.setSizePolicy(sizePolicy)
        self.LE_reponse.setMinimumSize(QtCore.QSize(415, 30))
        self.LE_reponse.setMaximumSize(QtCore.QSize(415, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LE_reponse.setFont(font)
        self.LE_reponse.setObjectName("LE_reponse")
        self.verticalLayout.addWidget(self.LE_reponse)
        self.label_verif = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_verif.sizePolicy().hasHeightForWidth())
        self.label_verif.setSizePolicy(sizePolicy)
        self.label_verif.setMinimumSize(QtCore.QSize(415, 30))
        self.label_verif.setMaximumSize(QtCore.QSize(415, 30))
        self.label_verif.setText("")
        self.label_verif.setAlignment(QtCore.Qt.AlignCenter)
        self.label_verif.setObjectName("label_verif")
        self.verticalLayout.addWidget(self.label_verif)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.bouton_solution = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bouton_solution.sizePolicy().hasHeightForWidth())
        self.bouton_solution.setSizePolicy(sizePolicy)
        self.bouton_solution.setMinimumSize(QtCore.QSize(120, 40))
        self.bouton_solution.setMaximumSize(QtCore.QSize(120, 40))
        self.bouton_solution.setObjectName("bouton_solution")
        self.horizontalLayout_3.addWidget(self.bouton_solution)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem6 = QtWidgets.QSpacerItem(17, 7, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bouton_nouvelle_partie = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_nouvelle_partie.setMinimumSize(QtCore.QSize(70, 70))
        self.bouton_nouvelle_partie.setMaximumSize(QtCore.QSize(70, 70))
        self.bouton_nouvelle_partie.setObjectName("bouton_nouvelle_partie")
        self.horizontalLayout.addWidget(self.bouton_nouvelle_partie)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.bouton_quitter = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bouton_quitter.sizePolicy().hasHeightForWidth())
        self.bouton_quitter.setSizePolicy(sizePolicy)
        self.bouton_quitter.setMinimumSize(QtCore.QSize(70, 70))
        self.bouton_quitter.setMaximumSize(QtCore.QSize(70, 70))
        self.bouton_quitter.setObjectName("bouton_quitter")
        self.horizontalLayout.addWidget(self.bouton_quitter)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Jeu des départements :</span></p><p align=\"center\"><span style=\" font-weight:600;\">trouvez à quel département appartient le numéro !</span></p></body></html>"))
        self.label_score.setText(_translate("MainWindow", "Score : x / 101"))
        self.label_question.setText(_translate("MainWindow", "TextLabel"))
        self.bouton_solution.setText(_translate("MainWindow", "Solution"))
        self.bouton_nouvelle_partie.setText(_translate("MainWindow", "Nouvelle\n"
"partie"))
        self.bouton_quitter.setText(_translate("MainWindow", "Quitter"))

